(source gnu)
(source melpa)

(depends-on "tramp")
(depends-on "company")
(depends-on "counsel")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "s")
(depends-on "smartparens")
(depends-on "use-package")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "google-this")
;;python
(depends-on "elpy")
(depends-on "virtualenvwrapper")
;;c/c++
(depends-on "cc-mode")
;;common lisp
(depends-on "slime")
(depends-on "haskell-mode")
;;haskell
(depends-on "lsp-mode")
(depends-on "lsp-ui" :git "https://github.com/emacs-lsp/lsp-ui.git")
(depends-on "lsp-haskell" :git "https://github.com/emacs-lsp/lsp-haskell.git")
;;clojure
(depends-on "cider")
(depends-on "clojure-mode")
(depends-on "clj-refactor")
(depends-on "rainbow-delimiters")
;;rust
(depends-on "rust-mode")
(depends-on "racer")
(depends-on "flycheck-rust")
;;web
(depends-on "web-mode")
(depends-on "company-web")
(depends-on "rjsx-mode")
(depends-on "impatient-mode")
(depends-on "json-mode")
;;docker
(depends-on "docker")
(depends-on "dockerfile-mode")
(depends-on "docker-compose-mode")
(depends-on "docker-tramp")
