(source gnu)
(source melpa)

(depends-on "company")
(depends-on "counsel")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "s")
(depends-on "smartparens")
(depends-on "use-package")
(depends-on "yasnippet")
(depends-on "auto-complete")
(depends-on "google-this")
;;python
(depends-on "elpy")
(depends-on "py-autopep8")
(depends-on "python-mode")
;;c/c++
(depends-on "cc-mode")
;;common lisp
(depends-on "slime")
(depends-on "haskell-mode")
;;haskell
(depends-on "lsp-mode")
(depends-on "lsp-ui" :git "https://github.com/emacs-lsp/lsp-ui.git")
(depends-on "lsp-haskell" :git "https://github.com/emacs-lsp/lsp-haskell.git")
;;clojure
(depends-on "cider")
(depends-on "clojure-mode")
;;rust
(depends-on "rust-mode")
(depends-on "racer")
;;web
(depends-on "web-mode")
(depends-on "company-web")
